disabled_rules:
  - trailing_whitespace
  - nesting
  - trailing_newline
line_length: 200
excluded:
  - Pods
  - Templates
  - AebOnlineAppIOS/Resources/Generated/R.generated.swift
  - AebOnlineAppIOSTests
  - AebOnlineAppIOSUITests
  - R.generated.swift
  - BVCAutoservice/Common/Extensions/UITableView/UITableView.swift
  - BVCAutoservice/Common/Extensions/UICollectionView/UICollectionView.swift
function_body_length:
  warning: 100
  error: 150
