disabled_rules:
  - trailing_whitespace
  - nesting
line_length: 200
excluded:
  - Pods
  - AebOnlineAppIOS/Resources/Generated/R.generated.swift
  - AebOnlineAppIOSTests
  - AebOnlineAppIOSUITests
  - R.generated.swift
